"""
notebooklm_pipeline/source_manifest.py — records which raw-package components
were actually uploaded to NotebookLM for a project, so a PE reading a gap in
the finished report can tell "the source document was never supplied at all"
apart from "the source was reviewed and is silent on this point."

The 631 Northland review conflated these two cases — every unresolved fact
read as a generic "» PE TO COMPLETE" regardless of whether NotebookLM ever
had a chance to find it. scripts/report_constants.py defines two distinct
outcomes for this reason:
    PE_MARKER            — sources were reviewed, judgment/field work needed
    MISSING_INPUT_MARKER — the source document itself wasn't in the package

This module only produces the human-readable Source_Manifest.md audit file
(present/absent per component); the actual "» MISSING INPUT: ..." markers in
report prose come from NotebookLM itself, instructed per-fact in specific
TemplateVault templates (see 03_User_Provided_Information.md's Title Records
/ Previous Reports sections and 05_Records_Review.md's City Directories
section) to distinguish the two cases when it can tell which applies.

Public interface:
    present_components(sources) -> set[str]
    build_manifest_markdown(sources) -> str
    write_source_manifest(project_path, sources) -> Path
"""

from __future__ import annotations

from pathlib import Path

from scripts.report_constants import KNOWN_COMPONENTS, UNDETECTABLE_INPUTS


def present_components(sources) -> set[str]:
    """sources: list[ingest.SourceInfo] (or anything with a `.component`
    attribute) — the components actually uploaded to NotebookLM."""
    return {s.component for s in sources}


def build_manifest_markdown(sources) -> str:
    """
    sources: list[ingest.SourceInfo], or None if this run resumed against an
    already-ingested notebook (--notebook-id) and never called run_ingest()
    itself this time — in that case we have no fresh data to report, so the
    manifest says so explicitly rather than guessing or fabricating "absent"
    for components that may well have been uploaded in the original run.
    """
    lines = [
        "# Source Manifest",
        "",
        "Auto-generated by `notebooklm_pipeline/source_manifest.py` — do not edit manually.",
        "",
        'Records which raw-package components were actually uploaded to NotebookLM for '
        'this project, so a gap in the report can be told apart as either '
        '"» MISSING INPUT" (the source document itself was never supplied) or '
        '"» PE TO COMPLETE" (the source was reviewed but silent on that point).',
        "",
        "## Standard appendix components",
        "",
    ]

    if sources is None:
        lines += [
            "_Not available — this run resumed against an already-ingested notebook "
            "(`--notebook-id`) and did not re-run ingestion. See the original run's "
            "Source_Manifest.md, if any._",
            "",
        ]
        return "\n".join(lines)

    present = present_components(sources)
    lines += ["| Component | Status | Required? |", "|---|---|---|"]
    for key, meta in KNOWN_COMPONENTS.items():
        status = "present" if key in present else "ABSENT"
        required = "**yes**" if meta["required"] else "optional"
        lines.append(f"| {meta['label']} | {status} | {required} |")

    missing_required = [
        meta["label"] for key, meta in KNOWN_COMPONENTS.items()
        if meta["required"] and key not in present
    ]
    if missing_required:
        lines += [
            "",
            f"**WARNING: required component(s) missing: {', '.join(missing_required)}.** "
            "The report's grounding for these facts will be minimal or absent.",
        ]

    lines += [
        "",
        "## Inputs not detectable from the standard appendix structure",
        "",
        "These commonly matter for a complete Phase 1 but do not arrive as their own "
        "numbered appendix in this raw-package format, so their presence/absence can't "
        "be automatically detected here — confirm separately whether the client/User "
        "supplied them:",
        "",
    ]
    for label in UNDETECTABLE_INPUTS.values():
        lines.append(f"- {label}")
    lines.append("")

    return "\n".join(lines)


def write_source_manifest(project_path: Path, sources) -> Path:
    project_path = Path(project_path)
    path = project_path / "Source_Manifest.md"
    path.write_text(build_manifest_markdown(sources), encoding="utf-8")
    return path
